global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'windows-pc'
    static_configs:
      - targets: ['host.docker.internal:9182']

  # --- PUSHGATEWAY JOB (REQUIRED) ---
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    honor_labels: true
    scrape_interval: 15s